/qsim/filename /home/sluddani/showerData/qsim_seed_TEST.root

/qsim/seed 12506 #change number to change random number seed


# Set run mode
/qsim/fDetMode 3 
/qsim/fStandMode 0
/qsim/fSourceMode 1
/qsim/fQMode 2

# Set detector properties
/qsim/fQuartzPolish 0.981
/qsim/fDetAngle 0 deg 
/qsim/fDetPosX 0 cm
/qsim/fDetPosY 0 cm

# set beam to "raster" 
 /qsim/xmin -5.625 cm
 /qsim/xmax 4.375 cm
# /qsim/ymin -12.3 cm
# /qsim/ymax 12.3 cm

/run/initialize

/qsim/emin   2.0056 GeV #beam energies
/qsim/emax   8.94939 GeV

/gun/particle e- #type of particle is an electron

/run/beamOn 100

